### ISSUE TITLE
Add Marathi Bible

### ISSUE THREAD

**Issue by opxdelwin** [godlytalias/Bible-Database#23]
Hey,

This repository is really great and is helping me with one of my projects! It'd be super great if you could add a marathi bible as well, as it's required by the project.

I have attached this sqlite3 file. Would be great if you could convert the schema into the common one that's being used by remaining of the bibles in this repo!!

Awaiting response,
This would mean the world to me.
Delwin

[ERV-mr.zip](https://github.com/godlytalias/Bible-Database/files/13416130/ERV-mr.zip)

**Comment by godlytalias** [comment]
Hey Delwin, Thanks for the kind words, As I checked the db, around 600 verses are having some errors and displays 'verse not available in translation', Do you have a database which is more reliable?
Regards,Godly
    On Monday, 20 November, 2023 at 08:18:27 pm IST, Delwin Mathew ***@***.***> wrote:  
 
 


Hey,

This repository is really great and is helping me with one of my projects! It'd be super great if you could add a marathi bible as well, as it's required by the project.

I have attached this sqlite3 file. Would be great if you could convert the schema into the common one that's being used by remaining of the bibles in this repo!!

Awaiting response,
This would mean the world to me.
Delwin

ERV-mr.zip

**Comment by opxdelwin** [comment]
I noted an issue where chapter numbering wasn't accurate.

Could you try extracting it the old way from wordproject.org?

**Comment by opxdelwin** [comment]
Here's the book numbers from the db file 
```
[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 190, 220, 230, 240, 250, 260, 290, 300, 310, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700, 710, 720, 730]
```

The noted discontinuity is between 
 - 160-190 (170, 180 missing)
 - 190-220 (200, 210 missing)
 - 260-290 (270, 280 missing)
 - 310-330 (320 missing)
 
 7 books are misaligned, hence 73-7 = 66

**Comment by opxdelwin** [comment]
is there any update @godlytalias ?

cc @sridharrajs

**Comment by godlytalias** [comment]
I will try to create it from wordproject, The database you gave have lot of discrepancies in the verses as well

**Comment by opxdelwin** [comment]
No worries, feel free to close the issue once done :)

**Comment by godlytalias** [comment]
@opxdelwin Marathi bible is added now, Please post the required corrections here

https://github.com/godlytalias/Bible-Database/tree/master/Marathi
