### ISSUE TITLE
What version is the English bible?

### ISSUE THREAD

**Issue by JesseSloan** [godlytalias/Bible-Database#5]
There are differences between the english bible you included and the King James Version.  For example:
Genesis 4:18 in your version reads "And Jared lived an hundred sixty and two years, and he **_brings forth_** Enoch:" while in the King james verison it reads ""And Jared lived an hundred sixty and two years, and he **_begat_** Enoch:"

Discrepancies like this are all over the place.  I understand that the English version you provided is perhaps not the King James Version.  However, you need to TELL US what version this actually is.

**Comment by godlytalias** [comment]
@JesseSloan Version used is **Updated King James Version**

References:
https://www.bibliaonline.com.br/ukjv/gn/4
https://www.godweb.org/kjv2/blGenesis.htm
http://www.ezreadbible.com/en_ukjv/ugenesis.htm#ch4
