### ISSUE TITLE
Verse Counts not following Afrikaans Bible's structure

### ISSUE THREAD

**Issue by Vennotius** [godlytalias/Bible-Database#8]
I went though your json version of the Afrikaans Bible to do some verification of verse counts for every chapter. My json version follows the Afrikaans Bible's structure.

I found the following differences between your("git") and my("m") version:
_([book number, book name, chapter number] - verse counts)_

02 Exodus 5 - m:24	git:23
02 Exodus 6 - m:29	git:30
09 I Samuel 20 - m:43	git:42
09 I Samuel 23 - m:28	git:29
09 I Samuel 24 - m:23	git:22
11 I Konings 2 - m:47	git:46
11 I Konings 22 - m:54	git:53
16 Nehemía 8 - m:19	git:18
18 Job 38 - m:38	git:41
18 Job 39 - m:38	git:30
18 Job 40 - m:28	git:24
18 Job 41 - m:25	git:34
19 Psalms 3 - m:9	git:8
19 Psalms 4 - m:9	git:8
19 Psalms 5 - m:13	git:12
19 Psalms 6 - m:11	git:10
19 Psalms 7 - m:18	git:17
19 Psalms 8 - m:10	git:9
19 Psalms 9 - m:21	git:20
19 Psalms 12 - m:9	git:8
19 Psalms 18 - m:51	git:50
19 Psalms 19 - m:15	git:14
19 Psalms 20 - m:10	git:9
19 Psalms 21 - m:14	git:13
19 Psalms 22 - m:32	git:31
19 Psalms 30 - m:13	git:12
19 Psalms 31 - m:25	git:24
19 Psalms 34 - m:23	git:22
19 Psalms 36 - m:13	git:12
19 Psalms 38 - m:23	git:22
19 Psalms 39 - m:14	git:13
19 Psalms 40 - m:18	git:17
19 Psalms 41 - m:14	git:13
19 Psalms 42 - m:12	git:11
19 Psalms 44 - m:27	git:26
19 Psalms 45 - m:18	git:17
19 Psalms 46 - m:12	git:11
19 Psalms 47 - m:10	git:9
19 Psalms 48 - m:15	git:14
19 Psalms 49 - m:21	git:20
19 Psalms 51 - m:21	git:19
19 Psalms 52 - m:11	git:9
19 Psalms 53 - m:7	git:6
19 Psalms 54 - m:9	git:7
19 Psalms 55 - m:24	git:23
19 Psalms 56 - m:14	git:13
19 Psalms 57 - m:12	git:11
19 Psalms 58 - m:12	git:11
19 Psalms 59 - m:18	git:17
19 Psalms 60 - m:14	git:12
19 Psalms 61 - m:9	git:8
19 Psalms 62 - m:13	git:12
19 Psalms 63 - m:12	git:11
19 Psalms 64 - m:11	git:10
19 Psalms 65 - m:14	git:13
19 Psalms 67 - m:8	git:7
19 Psalms 68 - m:36	git:35
19 Psalms 69 - m:37	git:36
19 Psalms 70 - m:6	git:5
19 Psalms 75 - m:11	git:10
19 Psalms 76 - m:13	git:12
19 Psalms 77 - m:21	git:20
19 Psalms 80 - m:20	git:19
19 Psalms 81 - m:17	git:16
19 Psalms 83 - m:19	git:18
19 Psalms 84 - m:13	git:12
19 Psalms 85 - m:14	git:13
19 Psalms 88 - m:19	git:18
19 Psalms 89 - m:53	git:52
19 Psalms 92 - m:16	git:15
19 Psalms 102 - m:29	git:28
19 Psalms 108 - m:14	git:13
19 Psalms 140 - m:14	git:13
19 Psalms 142 - m:8	git:7
20 Spreuke 23 - m:36	git:35
21 Prediker 4 - m:17	git:16
21 Prediker 5 - m:19	git:20
23 Jesaja 8 - m:23	git:22
23 Jesaja 9 - m:20	git:21
27 Daniël 5 - m:30	git:31
27 Daniël 6 - m:29	git:28
28 Hoséa 1 - m:12	git:11
28 Hoséa 2 - m:22	git:23
28 Hoséa 11 - m:11	git:12
28 Hoséa 12 - m:15	git:14
28 Hoséa 13 - m:15	git:16
28 Hoséa 14 - m:10	git:9
33 Miga 4 - m:14	git:13
33 Miga 5 - m:14	git:15
43 Johannes 1 - m:52	git:51
44 Handelinge 19 - m:40	git:41
45 Romeine 7 - m:26	git:25
47 II Korinthiërs 13 - m:13	git:14
64 III Johannes 1 - m:15	git:14
66 Openbaring 12 - m:18	git:17

**Upon inspection, I found things like the following:**

1. _Multiple verses in one verse entry:_  

- {'Verseid': '44006024', 'Verse': 'Ek dank God deur Jesus Christus, onse Here! **(7:26)** So dien ek self dan wel met die gemoed die wet van God, maar met die vlees die wet van die sonde."'}

- {'Verseid': '63000013', 'Verse': 'Maar ek hoop om jou gou te sien, en ons sal van mond tot mond spreek. **(1:15)** Vrede vir jou! Die vriende groet jou. Groet die vriende by die naam."'}

- {'Verseid': '65012000', 'Verse': '**(12:18)** En ek het op die sand van die see gaan staan. **(13:1)** En ek het ‘n dier uit die see sien opkom met sewe koppe en tien horings, en op sy horings tien krone en op sy koppe ‘n naam van godslastering."'}

2. _Json chapter entry spanning two Bible chapters:_

- {'Verseid': '17039004',
   'Verse': '(39:38) Een maal het ek gespreek, maar sal nie meer antwoord nie; ja, twee maal, maar ek sal nie voortgaan nie."'},
- {'Verseid': '17039005',
   'Verse': '(40:1) En die HERE het Job uit ‘n storm geantwoord en gesê:"'},

Is there a specific reason for doing it this way? Is this a design choice? I do not want to propose a fixes if it will break your design/intention.

**Comment by godlytalias** [comment]
@Vennotius Thanks a lot for your feedback. These databases were generated using some scripts and probably this was a mistake occured in scripts. If you have a fix for these please feel free to raise a pull request. Or else I will go through these listed verses and will fix those, Thank you

**Comment by Vennotius** [comment]
OK, cool.

I will make fixes. I have not ever made pull requests, so please have patience if I don't do it right... Hehe
